name: Secure CI/CD Pipeline

on:
  push:
    branches:
      - main
      - awsci

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential openssl awscli -y

      - name: Build C Binary
        run: |
          gcc src/main.c -o app_binary

      - name: Generate PKI Certificates
        run: |
          chmod +x pki/generate_ca.sh
          ./pki/generate_ca.sh

      - name: Sign Binary
        run: |
          openssl dgst -sha256 -sign rootCA.key -out binary.sig app_binary

      - name: Verify Signature
        run: |
          openssl x509 -pubkey -noout -in rootCA.pem > public.pem
          openssl dgst -sha256 -verify public.pem -signature binary.sig app_binary

      - name: Configure AWS Credential
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Upload Artifacts to S3
        run: |
          aws s3 cp app_binary s3://${{ secrets.S3_BUCKET }}/
          aws s3 cp binary.sig s3://${{ secrets.S3_BUCKET }}/

      - name: Build Docker Image
        run: |
          docker build -t secure-ci-demo .
